### ISSUE TITLE
In the toolbar template, fixed text is being used. I would like it to be changed to a variable

### ISSUE THREAD

**Issue by yamachan428** [hunghg255/quill-resize-image#1]
Hi.
Thank you always for the helpful content.

Below, the tooltip portion of the toolbar template, `<span class=\"tooltip\">Press enter key to apply change!</span>`, is a fixed string.
Could you please change it to a variable (probably {5})?
https://github.com/hunghg255/quill-resize-image/blob/643a5a26b4274358df953faa88121fae28c37866/dist/quill-resize-image.js#L106-L106

**Comment by hunghg255** [comment]
thanks for the feedback @yamachan428. I updated it, you can check new version

**Comment by yamachan428** [comment]
@hunghg255 
thanks for the update.
I have confirmed that it is working as expected
