### ISSUE TITLE
image properties resets when you open the html using the editor again

### ISSUE THREAD

**Issue by AntenehTilaye** [hunghg255/quill-resize-image#2]
all features works, but when i reload the formatted text in the editor again, the style will be removed

**Comment by hunghg255** [comment]
@AntenehTilaye Im not issued, can you send me a mini repoduce

**Comment by hunghg255** [comment]
@AntenehTilaye i built a editor from tiptap. you can check https://github.com/hunghg255/rc-tiptap-editor
