### ISSUE TITLE
Resize only is not recognized as a change

### ISSUE THREAD

**Issue by juliandierker** [hunghg255/quill-resize-image#3]
Hey guys. I experience that sometimes when you only resize the img without changing the content - there wont be an onChange triggered once.

![image](https://github.com/hunghg255/quill-resize-image/assets/18357175/c8f7afc0-9bd1-4377-8aa5-ada8a573133d)

When I only resize here. Sometimes it won't get recognize as a change and this value of quillEditor 

`<p class="ql-align-right">ffdsfdsfdsdfdsfdsdsadfdsfdsf<img src="http://localhost:8080/uploads/66586ecc3a29a2edf934a3b1" width="122" style="">b<span class="ql-font-Roboto">﻿</span></p>`

width and height stays the same.

Thanks for your support.

**Comment by hunghg255** [comment]
@juliandierker I built en editor from tiptap. you can check https://github.com/hunghg255/rc-tiptap-editor
